
# Dependencies
markdown:         kramdown

# Permalinks
#permalink:        pretty

# Setup
title:            'Physics'
tagline:          'from http://cnx.org/contents/031da8d3-b525-429c-80cf-6c8ed997733a@9.58 (CC-BY)'
url:              https://github.com/philschatz/physics-book
origin:           http://cnx.org/contents/031da8d3-b525-429c-80cf-6c8ed997733a@9.58

author:
  name:           'Openstax'
  url:            https://github.com/openstax

paginate:         5

# Custom vars
version:          9.58

bookviewer:       http://philschatz.com/book-viewer

